### ISSUE TITLE
Roadmap of this package?

### ISSUE THREAD

**Issue by happyshows** [DivadNojnarg/shinydashboardPlus#2]
Hi,

Firstly, this package looks great, covering a lot enhancement that should have been covered by shinydashboard.

I'd like to know plan for this package and shinybulma and maybe others you are actively building?
Will shinydashboard+ work with bulma & external packages like shinyWidgets (bootstrap based of course)?

I don't find other place to file this question, so bare with me..

**Comment by DivadNojnarg** [comment]
Dear Happyshows,

Thank you for your comment. Regarding this package:

- you may know that shinydashboard is built upon adminLTE2 (boostrap 3 dashboard template). By default, shinydashboard included a lot of elements from adminLTE. It is also very well written such that you can easily customize it. In this package I almost included everything you can find in adminLTE2 (rightsidebar, ...). Therefore, there is not so much to do next (regarding new features). However, I still have to implement all the render functions to make it straightforward to generate elements programmatically (like renderValueBox in shinydashboard; based on renderUi):

```
renderValueBox <- function(expr, env = parent.frame(), quoted = FALSE) {
  # Convert the expression to a function
  vbox_fun <- shiny::exprToFunction(expr, env, quoted)

  # Wrap that function in another function which strips off the outer div and
  # send it to renderUI.
  shiny::renderUI({
    vbox <- vbox_fun()
    tagAssert(vbox, type = "div")

    # Strip off outer div, since it's already present in output
    vbox$children[[1]]
  })
}
```

- Boostrap 4 is out and there is an adminLTE3 alpha version based on this new framework (https://github.com/almasaeed2010/AdminLTE/releases/tag/v3.0.0-alpha). Besides,
Nate Teetor (https://github.com/nteetor/dull) is creating a package called dull, which is a bootstrap 4 version of shiny (because shiny is based on BS3). Once everything is ok, I think it is possible to move shinydashboard to boostrap 4 using dull as well as adminLTE3.

- I am not the creator of shinybulma, I just authored some of the functions (carousel, timeline, boxes, right sidebar, ...). You could ask John Coene who is the creator. As far as I know, there is still a lot to do :) (Note that in the current version of shinybulma, some functions are not working because of a CSS dependency problem, which has to be fixed. If you want to use bulmaExtensions, you can download the package from my forked repository).

- You can definitely use shinyWigdets by @pvictor either in shinybulma or shinydashboardPlus. 
shinyWidgets is one of my favorite add-on for shiny. New functions like chooseSliderSkin and setSliderColor can help you to create nice sliders (different from basic shiny).

- I have projects for shinymaterial (similar to shinydashboardPlus), because a lot of materialize elements are missing from shinymaterial (https://ericrayanderson.github.io/shinymaterial/)

I hope it answers some of your questions.

Cheers

David

**Comment by happyshows** [comment]
Sounds great, thanks.
